-- ============================================================
-- Revaltus Onboarding — WordPress blog-sync site registry
-- Run this entire file in Supabase → SQL Editor.
-- ============================================================
-- Backs the transition-period WordPress blog-sync bridge. Each row is one
-- self-hosted WordPress site that pulls published blog posts from a client's
-- git repo via GET /api/wp-feed/{site_key}. Managed entirely from the admin UI
-- (Admin → WordPress Sites); replaces the earlier config/wordpress-sites.json.
--
-- The bearer `secret` is generated by the app on create/regenerate and shown to
-- the operator once to paste into the WordPress plugin. Service-role access only
-- (routes gate via requireAdminUser); RLS is enabled with NO policies, matching
-- the app-code-enforced scoping model used by task_progress (migration 057).
-- ============================================================

create table wordpress_sites (
  id uuid primary key default gen_random_uuid(),
  site_key text not null unique,          -- URL slug: /api/wp-feed/{site_key}
  github_repo text not null,              -- "repo" or "owner/repo" (like content_jobs.github_repo)
  enabled boolean not null default true,  -- per-site kill switch (disabled → feed 404s)
  secret text not null,                   -- app-generated bearer token (shown once on create/regenerate)
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table wordpress_sites enable row level security;
