import { describe, expect, it } from 'vitest'
import { lintOverrides } from './overrides-lint'

describe('lintOverrides', () => {
  it('flags template-owned shadows, Tailwind-keyed selectors, colour literals and !important', () => {
    const css = `/* Generated by Claude Design */
[data-component="footer"] { background: var(--color-primary); }
[data-component="footer"] img { filter: brightness(0) invert(1); }
a.bg-action, button.bg-action { padding: 8px 20px !important; height: auto !important; border-radius: var(--radius-sm); }
.bg-background\\/95 { backdrop-filter: blur(4px); }
[class*="bg-primary"] h2 { color: rgba(99, 45, 84, 0.9); }
.t-kicker { color: #632d54; }
@media (min-width: 768px) { .hero { --local: #fff; margin: 0; } }
`
    const r = lintOverrides(css)
    expect(r.ownedShadows).toBe(6) // footer bg, footer img filter, button padding/height/radius, kicker colour
    expect(r.tailwindSelectors).toBe(3) // a.bg-action…, .bg-background\/95, [class*=]
    expect(r.colorLiterals).toBe(2) // rgba(…) + #632d54 (custom-property values are ignored)
    expect(r.important).toBe(2)
    expect(r.staleStub).toBe(false)
  })

  it('detects the stale export-brief stub comment; empty file is clean', () => {
    expect(lintOverrides('/* run `npm run export-brief` to refresh */\n').staleStub).toBe(true)
    expect(lintOverrides(null)).toMatchObject({ lines: 0, findings: [] })
  })
})
