// Regenerate a client site's src/app/fonts.generated.ts from design.json
// typography — a PURE, byte-for-byte port of the template's
// src/lib/theme/font-module.ts (counting-five-client-template). The platform
// owns this because the template does not regenerate the module on deploy:
// it is a committed file, so a font change must ship the regenerated module
// alongside design.json. The golden-fixture test guards drift. Pure +
// client-safe. `generateAllFontsModule` is template-CI-only and NOT ported.
//
// Two header kinds (mirrors the template's PF5 handling). generateFontsModule()
// with NO argument emits the DEFAULT kind: the template's default fonts
// (today's live fonts), seeded on rollout and never held to design.json
// parity. generateFontsModule(typography) — including `{}` — emits the SYNCED
// kind: generated from design.json. fontsModuleKind(source) tells them apart
// and is CRLF-tolerant (a trailing \r on the first line is ignored) so a
// CRLF checkout still classifies correctly.
import { DEFAULT_TYPOGRAPHY, FONT_MANIFEST, MONO_FAMILY, type FontManifestEntry } from './font-manifest'

export type FontRole = 'heading' | 'body' | 'accent' | 'mono'
export type FontTypographyInput = { headingFont?: string; bodyFont?: string; accentFont?: string }

type RoleSpec = { role: FontRole; variable: string; weights: readonly string[]; italic: boolean }
export const ROLE_SPECS: readonly RoleSpec[] = [
  { role: 'heading', variable: '--font-heading-loaded', weights: ['400', '500', '700'], italic: false },
  { role: 'body', variable: '--font-body-loaded', weights: ['400', '500', '700'], italic: false },
  { role: 'accent', variable: '--font-accent-loaded', weights: ['400', '500'], italic: true },
  { role: 'mono', variable: '--font-mono-loaded', weights: ['400', '500'], italic: false },
]

export type FontsModuleKind = 'default' | 'synced'

export const FONTS_MODULE_HEADERS: Readonly<Record<FontsModuleKind, readonly string[]>> = {
  default: [
    '// This file is generated by scripts/generate-fonts.ts — default — not synced from design.json.',
    '// It loads the template default fonts; run `npm run generate-fonts` to sync it to content/design.json (typography).',
    '// The Revaltus platform rewrites it when the site fonts change (Design Studio / Theme Studio).',
  ],
  synced: [
    '// This file is generated by scripts/generate-fonts.ts from content/design.json.',
    '// Edit design.json (typography) and run `npm run generate-fonts` instead of editing it.',
    '// The Revaltus platform rewrites it when the site fonts change (Design Studio / Theme Studio).',
  ],
}

/**
 * Which kind of generated module `source` is, by its first line; null if neither.
 * A trailing \r is ignored so a CRLF checkout (git autocrlf) still classifies.
 */
export function fontsModuleKind(source: string): FontsModuleKind | null {
  const first = source.split('\n', 1)[0].replace(/\r$/, '')
  if (first === FONTS_MODULE_HEADERS.default[0]) return 'default'
  if (first === FONTS_MODULE_HEADERS.synced[0]) return 'synced'
  return null
}

type Load = { entry: FontManifestEntry; variable: string; weights: Set<string>; italic: boolean }

const entryFor = (family: string | undefined): FontManifestEntry | undefined =>
  FONT_MANIFEST.find((e) => e.family === family)

function resolveFamilies(t: FontTypographyInput): { families: Record<FontRole, FontManifestEntry>; warnings: string[] } {
  const warnings: string[] = []
  const pick = (role: FontRole, wanted: string | undefined, fallback: string): FontManifestEntry => {
    const found = entryFor(wanted)
    if (found) return found
    if (wanted) warnings.push(`Unknown ${role} font "${wanted}" — using ${fallback}.`)
    return entryFor(fallback) as FontManifestEntry
  }
  return {
    families: {
      heading: pick('heading', t.headingFont, DEFAULT_TYPOGRAPHY.headingFont),
      body: pick('body', t.bodyFont, DEFAULT_TYPOGRAPHY.bodyFont),
      accent: pick('accent', t.accentFont, DEFAULT_TYPOGRAPHY.accentFont),
      mono: entryFor(MONO_FAMILY) as FontManifestEntry,
    },
    warnings,
  }
}

const byWeight = (a: string, b: string): number => Number(a) - Number(b)

function renderCall(name: string, load: Load): string {
  const weights = [...load.weights].sort(byWeight)
  return [
    `const ${name} = ${load.entry.importName}({`,
    `  subsets: ['latin'],`,
    `  weight: [${weights.map((w) => `'${w}'`).join(', ')}],`,
    ...(load.italic ? [`  style: ['normal', 'italic'],`] : []),
    `  variable: '${load.variable}',`,
    `  display: 'swap',`,
    `})`,
  ].join('\n')
}

function renderModule(header: readonly string[], loads: Load[], aliases: [string, string][]): string {
  const variables = loads.map((_, i) => `\${font${i}.variable}`).join(' ')
  const aliasDecl =
    aliases.length === 0
      ? 'export const fontAliases: CSSProperties = {}'
      : [
          'export const fontAliases: CSSProperties = {',
          ...aliases.map(([v, target]) => `  '${v}': 'var(${target})',`),
          '} as CSSProperties',
        ].join('\n')
  return [
    ...header,
    '',
    "import type { CSSProperties } from 'react'",
    `import { ${loads.map((l) => l.entry.importName).join(', ')} } from 'next/font/google'`,
    '',
    loads.map((l, i) => renderCall(`font${i}`, l)).join('\n\n'),
    '',
    '/** next/font variable classes for <html className>. */',
    `export const fontVariables = \`${variables}\``,
    '',
    '/** Roles sharing a family point at the loaded variable (applied as <html style>). */',
    aliasDecl,
    '',
  ].join('\n')
}

/**
 * No argument → the DEFAULT kind (template default fonts). A typography object
 * (even `{}`, e.g. a design.json without typography) → the SYNCED kind.
 */
export function generateFontsModule(t?: FontTypographyInput): { source: string; warnings: string[] } {
  const { families, warnings } = resolveFamilies(t ?? {})
  const loads: Load[] = []
  const aliases: [string, string][] = []
  for (const spec of ROLE_SPECS) {
    const entry = families[spec.role]
    const supported = spec.weights.filter((w) => entry.weights.includes(w))
    const existing = loads.find((l) => l.entry.family === entry.family)
    if (existing) {
      for (const w of supported) existing.weights.add(w)
      existing.italic = existing.italic || (spec.italic && entry.italic)
      aliases.push([spec.variable, existing.variable])
      continue
    }
    loads.push({
      entry,
      variable: spec.variable,
      weights: new Set(supported.length > 0 ? supported : [entry.weights[0]]),
      italic: spec.italic && entry.italic,
    })
  }
  return { source: renderModule(FONTS_MODULE_HEADERS[t === undefined ? 'default' : 'synced'], loads, aliases), warnings }
}
