import { readFileSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { CURATED_FONTS } from './type-pairing-catalog'
import { FONT_MANIFEST, fontManifestJson } from './font-manifest'
import { FONTS_MODULE_HEADERS, fontsModuleKind, generateFontsModule } from './font-module-generator'

// Goldens are the ACTUAL output of the template's scripts/generate-fonts.ts
// (counting-five-client-template src/lib/theme/__fixtures__/fonts/), copied
// verbatim — the same drift guard as theme.css.golden. If the template
// generator changes, re-copy and port together.
const FIX = path.join(__dirname, '__fixtures__')
const read = (f: string) => readFileSync(path.join(FIX, f), 'utf-8')

describe('font manifest parity', () => {
  it('matches the template docs/design/font-manifest.json byte for byte', () => {
    expect(fontManifestJson()).toBe(read('font-manifest.template.json'))
  })
  it('covers every curated font (the only fonts the platform writes)', () => {
    const families = FONT_MANIFEST.map((e) => e.family)
    for (const f of CURATED_FONTS) expect(families).toContain(f)
  })
})

describe('generateFontsModule (byte parity with the template)', () => {
  it('no-arg call → the DEFAULT kind → the template default module golden', () => {
    expect(generateFontsModule().source).toBe(read('fonts-default.golden.txt'))
  })
  it.each(['editorial', 'noitalic'])('%s fixture (SYNCED kind) → its golden', (name) => {
    const design = JSON.parse(read(`design-fonts-${name}.json`)) as { typography: Record<string, string> }
    expect(generateFontsModule(design.typography).source).toBe(read(`fonts-${name}.golden.txt`))
  })
  it('never warns for a curated font', () => {
    for (const f of CURATED_FONTS) expect(generateFontsModule({ headingFont: f, bodyFont: f, accentFont: f }).warnings).toEqual([])
  })
})

describe('fontsModuleKind / FONTS_MODULE_HEADERS (mirrors the template exactly)', () => {
  it('classifies the default golden as "default" and the synced goldens as "synced"', () => {
    expect(fontsModuleKind(read('fonts-default.golden.txt'))).toBe('default')
    expect(fontsModuleKind(read('fonts-editorial.golden.txt'))).toBe('synced')
    expect(fontsModuleKind(read('fonts-noitalic.golden.txt'))).toBe('synced')
  })
  it('no-arg produces the default header; an explicit typography object (even {}) produces the synced header', () => {
    expect(fontsModuleKind(generateFontsModule().source)).toBe('default')
    expect(fontsModuleKind(generateFontsModule({}).source)).toBe('synced')
  })
  it('is CRLF-tolerant (a trailing \\r on the first line still classifies)', () => {
    const crlf = generateFontsModule().source.replace(/\n/g, '\r\n')
    expect(fontsModuleKind(crlf)).toBe('default')
  })
  it('returns null for an unrecognised or hand-edited header', () => {
    expect(fontsModuleKind('// hand-edited\n')).toBeNull()
    expect(fontsModuleKind('')).toBeNull()
  })
  it('FONTS_MODULE_HEADERS matches the template verbatim', () => {
    expect(FONTS_MODULE_HEADERS).toEqual({
      default: [
        '// This file is generated by scripts/generate-fonts.ts — default — not synced from design.json.',
        '// It loads the template default fonts; run `npm run generate-fonts` to sync it to content/design.json (typography).',
        '// The Revaltus platform rewrites it when the site fonts change (Design Studio / Theme Studio).',
      ],
      synced: [
        '// This file is generated by scripts/generate-fonts.ts from content/design.json.',
        '// Edit design.json (typography) and run `npm run generate-fonts` instead of editing it.',
        '// The Revaltus platform rewrites it when the site fonts change (Design Studio / Theme Studio).',
      ],
    })
  })
})
