import { Page, View, Text, StyleSheet } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page:     { padding: 48, backgroundColor: '#ffffff' },
  header:   { marginBottom: 32, paddingBottom: 20, borderBottom: '2pt solid #003B71' },
  title:    { fontSize: 26, fontWeight: 'bold', color: '#003B71', marginBottom: 6 },
  subtitle: { fontSize: 13, color: '#64748B' },
  section:  { marginBottom: 8 },
  label:    { fontSize: 9, color: '#94A3B8', marginBottom: 2 },
  value:    { fontSize: 12, color: '#1E293B' },
  footer:   { position: 'absolute', bottom: 40, left: 48, right: 48 },
  footerText: { fontSize: 9, color: '#94A3B8', textAlign: 'center' },
})

type Schema = Record<string, unknown>

function Field({ label, value }: { label: string; value: string | undefined }) {
  if (!value) return null
  return (
    <View style={styles.section}>
      <Text style={styles.label}>{label.toUpperCase()}</Text>
      <Text style={styles.value}>{value}</Text>
    </View>
  )
}

export function CoverPage({ schema, approvedAt }: { schema: Schema; approvedAt: string | null }) {
  const contact = schema.contact as Record<string, string> | undefined
  const business = schema.business as Record<string, string> | undefined

  return (
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>{business?.name ?? 'Unnamed Firm'}</Text>
        <Text style={styles.subtitle}>Website Intake Summary</Text>
      </View>

      <Field label="Website" value={schema.websiteUrl as string} />
      <Field label="Contact" value={contact ? `${contact.firstName ?? ''} ${contact.lastName ?? ''}`.trim() : undefined} />
      <Field label="Email" value={contact?.email} />
      <Field label="Phone" value={contact?.phone} />
      <Field label="Date Approved" value={approvedAt ? new Date(approvedAt).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) : undefined} />

      <View style={styles.footer}>
        <Text style={styles.footerText}>Generated by CountingFive Onboarding — Confidential</Text>
      </View>
    </Page>
  )
}
